modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Traverse-Joe/Baubley-Heart-Canisters/issues"

[[mods]]
modId="bhc"
version="${file.jarVersion}"
displayName="Baubley Heart Canisters"
credits="Thanks goes to UpcraftLP who helped with original build. Also Abused_Master for helping when i bugged him."
authors="Traverse_Joe"
description='''
Heart Canisters for Baubles/Curios Enjoy :D
'''

[[dependencies.bhc]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"